apiVersion: v1
kind: Pod
metadata:
  name: ngnix
  labels:
    app: ngnix
spec:
  containers:
  - name: ngnixcont
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  type: ClusterIP
  selector:
    app: ngnix 
ports:
- port: 80
  targetPort: 80         


