apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mavendep
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: mavenwebbapp
  startegy:
    type: Recreate    
  template: 
    metadata: 
      name: mavenwebbapppod
      labels: 
        app: mavenwebbapp
    spec: 
      containers: 
      - image: prathapva/maven-web-application:1
        name: mavenwebappcontainer
        ports: 
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavendeprs
spec:
  type: NodePort
  selector:
     app: mavenwebbapp
  ports:
  - port: 80
    targetPort: 8080