apiVersion: v1
kind: Pod
metadata:
  name: httpdpod
  labels:
    app: httpd
spec:
  containers:
  - name: httpdcont
    image: httpd
    ports:
    - containerPort: 80
---
apiVersion:
kind: Service
metadata:
  name: httpdsvc
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
  - port: 80
    targetPort: 80

            