apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsd
spec:
  selector:
    matchLabels:
      app: jenkinsapp
  template:
    metadata:
      labels:
        app: jenkinsapp
    spec:
      containers:
      - name: jenkinscontiner
        image: jenkins/jenkins:lts
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkinsvol
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkinsvol
        persistentVolumeClaim:
          claimName: jenkinspvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinspvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: jenkinssvc
spec:
  type: NodePort
  selector:
    app: jenkinsapp
  ports:
  - port: 80
    targetPort: 8080  
