apiVersion: v1
kind: PersistentVolume 
metadata:
  name: nfspvc
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.38.180
    path: /mnt/nfs_share