apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenappdep
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenapp
  template:
    metadata:
      labels: 
        app: mavenapp
    spec:
      affinity:
        nodeaffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key:
                operators: In
                values:
                - workerone
      containers:
      - name: mavencont
        image: prathapva/maven-web-application:1
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: mavenapp
  ports:
  - port: 80
    targetPort: 8080                     