apiVersion: v1
kind: Pod
metadata:
  name: mavenwebpod
  labels:
   app: mavenwebapp
spec: 
  containers: 
  - name: mavenwebapp
    image: prathapva/maven-web-application:1
    ports: 
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebsvc
spec: 
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
  - port: 8080
    targetPort: 8080      
