apiVersion: v1
kind: Pod
metadata:
  name: nodejspod
  labels:
    app: nodeapp
spec:
  containers:
  - name: nodejswebapp
    image: prathapva/nodejs:1
    ports:
    - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodejssvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
  - port: 80
    targetPort: 9981    

