apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebdep
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: mavenwebapp
  startegy: 
    type: Recreate
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcont
        image: prathapva/maven-web-application:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebsvc
spec:
  type: NodePort
selector:
  app: mavenwebapp
ports:
- port: 80
  targetPort: 8080


               